// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fighters_api.Data;

namespace fighters_api.Migrations
{
    [DbContext(typeof(FightContext))]
    [Migration("20220419094336_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("fighters_api.Data.Fight", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("blue_fighterid")
                        .HasColumnType("int");

                    b.Property<int?>("red_fighterid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("blue_fighterid");

                    b.HasIndex("red_fighterid");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("fighters_api.Data.Fighter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Fighter");
                });

            modelBuilder.Entity("fighters_api.Data.Fight", b =>
                {
                    b.HasOne("fighters_api.Data.Fighter", "blue_fighter")
                        .WithMany()
                        .HasForeignKey("blue_fighterid");

                    b.HasOne("fighters_api.Data.Fighter", "red_fighter")
                        .WithMany()
                        .HasForeignKey("red_fighterid");

                    b.Navigation("blue_fighter");

                    b.Navigation("red_fighter");
                });
#pragma warning restore 612, 618
        }
    }
}
